# basic commands of importing and creation of the DataFrame

In [ ]:
import numpy as np
import pandas as pd


In [ ]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
# create data frame== dataframe is a kind of data structure used in the paython simllar to arry
df=pd.DataFrame(data=np.arange(0,20).reshape(5,4),index=["row1","row2","row3","row4","row5"],columns=["column1","column2","column3","column4"])

In [ ]:
print(df)

      column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19


In [ ]:
df.head()# by defoult it shows top 5 records and i can also sselect the number of the records by manually mentioned the number of the records

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
df.tail()#by defoult is shows last 5 records

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
type(df)# say about the data type of df

pandas.core.frame.DataFrame

In [ ]:
df.info()# this gives some inforamation anout the data frame like data type  of the columns

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, row1 to row5
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   column1  5 non-null      int64
 1   column2  5 non-null      int64
 2   column3  5 non-null      int64
 3   column4  5 non-null      int64
dtypes: int64(4)
memory usage: 372.0+ bytes


In [ ]:
df.describe()# gives some calculated value that helps us to find some measure of centralitis note this inbuilt function  only works with the int

column1    column2    column3    column4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

# indexing and its diffrent methods

In [ ]:
df.head()

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

# column indexing

In [ ]:
df['column1']# sigle row or single coulum cosiderd as (pandas series)

row1     0
row2     4
row3     8
row4    12
row5    16
Name: column1, dtype: int64

In [ ]:
df[['column1','column2','column3']]# in case of multiple column mentioned them inside a list
# multiple rows and multiple coulmns considerd as (pandas datadframe)
# for more check there data type using functon type()

column1  column2  column3
row1        0        1        2
row2        4        5        6
row3        8        9       10
row4       12       13       14
row5       16       17       18

from matplotlib import pyplot as plt
_df_0['column1'].plot(kind='hist', bins=20, title='column1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_1['column2'].plot(kind='hist', bins=20, title='column2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_2['column3'].plot(kind='hist', bins=20, title='column3')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_3.plot(kind='scatter', x='column1', y='column2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_4.plot(kind='scatter', x='column2', y='column3', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['column1']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'column1'}, axis=1)
              .sort_values('column1', ascending=True))
  xs = counted['column1']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_5.sort_values('column1', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('column1')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['column2']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'column2'}, axis=1)
              .sort_values('column2', ascending=True))
  xs = counted['column2']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_6.sort_values('column2', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('column2')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['column3']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'column3'}, axis=1)
              .sort_values('column3', ascending=True))
  xs = counted['column3']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_7.sort_values('column3', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('column3')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_8['column1'].plot(kind='line', figsize=(8, 4), title='column1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_9['column2'].plot(kind='line', figsize=(8, 4), title='column2')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_10['column3'].plot(kind='line', figsize=(8, 4), title='column3')
plt.gca().spines[['top', 'right']].set_visible(False)

# row indexing using loc parameter

In [ ]:
df.loc[["row3","row4"]]

column1  column2  column3  column4
row3        8        9       10       11
row4       12       13       14       15

from matplotlib import pyplot as plt
_df_11['column1'].plot(kind='hist', bins=20, title='column1')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_12['column2'].plot(kind='hist', bins=20, title='column2')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_13['column3'].plot(kind='hist', bins=20, title='column3')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_14['column4'].plot(kind='hist', bins=20, title='column4')
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_15.plot(kind='scatter', x='column1', y='column2', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_16.plot(kind='scatter', x='column2', y='column3', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
_df_17.plot(kind='scatter', x='column3', y='column4', s=32, alpha=.8)
plt.gca().spines[['top', 'right',]].set_visible(False)

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['column1']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'column1'}, axis=1)
              .sort_values('column1', ascending=True))
  xs = counted['column1']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_18.sort_values('column1', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('column1')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['column2']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'column2'}, axis=1)
              .sort_values('column2', ascending=True))
  xs = counted['column2']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_19.sort_values('column2', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('column2')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['column3']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'column3'}, axis=1)
              .sort_values('column3', ascending=True))
  xs = counted['column3']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_20.sort_values('column3', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('column3')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
import seaborn as sns
def _plot_series(series, series_name, series_index=0):
  palette = list(sns.palettes.mpl_palette('Dark2'))
  counted = (series['column4']
                .value_counts()
              .reset_index(name='counts')
              .rename({'index': 'column4'}, axis=1)
              .sort_values('column4', ascending=True))
  xs = counted['column4']
  ys = counted['counts']
  plt.plot(xs, ys, label=series_name, color=palette[series_index % len(palette)])

fig, ax = plt.subplots(figsize=(10, 5.2), layout='constrained')
df_sorted = _df_21.sort_values('column4', ascending=True)
_plot_series(df_sorted, '')
sns.despine(fig=fig, ax=ax)
plt.xlabel('column4')
_ = plt.ylabel('count()')

from matplotlib import pyplot as plt
_df_22['column1'].plot(kind='line', figsize=(8, 4), title='column1')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_23['column2'].plot(kind='line', figsize=(8, 4), title='column2')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_24['column3'].plot(kind='line', figsize=(8, 4), title='column3')
plt.gca().spines[['top', 'right']].set_visible(False)

from matplotlib import pyplot as plt
_df_25['column4'].plot(kind='line', figsize=(8, 4), title='column4')
plt.gca().spines[['top', 'right']].set_visible(False)

# indexing using combination of the rwo and column indexing

In [ ]:
df.iloc[2:4,0:2]# this prints row(3 and 4) and column(1 and 2)
# note= mentioned the index using conventional indexing method (start from the 0 for both rown and column)

column1  column2
row3        8        9
row4       12       13

In [ ]:
df.iloc[2:,1:]# ending constrain can be assumed by the algo

column2  column3  column4
row3        9       10       11
row4       13       14       15
row5       17       18       19

# converting dataframe into the array

In [ ]:
df.iloc[:,1:].values

array([[ 1,  2,  3],
       [ 5,  6,  7],
       [ 9, 10, 11],
       [13, 14, 15],
       [17, 18, 19]])

# basic operations  n pandas

In [ ]:
df# this will also prints  the dataframe named df

column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [ ]:
print(df)

      column1  column2  column3  column4
row1        0        1        2        3
row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19


In [ ]:
df.isnull().sum()# this gives 1 infront of respective column if a null value is founded

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [ ]:
df['column3'].value_counts()# gives diffrent values and there frequencies of elements presents in the column3

2     1
6     1
10    1
14    1
18    1
Name: column3, dtype: int64

In [ ]:
df['column1'].unique()# gives array of all the unque values in that perticular column

array([ 0,  4,  8, 12, 16])

# working and importing csv files

In [4]:
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/dataset/mercedesbenz (1).csv')

# Print the DataFrame
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [ ]:
type(df)

pandas.core.frame.DataFrame

note= as read_csv() requried file  formate data  to import and make it data frame thats why  we need to make it the (in memory file formate object) using stringIO()

In [ ]:
from  io import StringIO
data=('col1,col2,col3\n'
      'x,y,z\n'
      'a,b,d\n'
      '1,2,3')

In [ ]:
type(data)

str

In [ ]:
StringIO(data)

In [ ]:
pd.read_csv(StringIO(data))# converting the str into in memory file formate

col1 col2 col3
0    x    y    z
1    a    b    d
2    1    2    3

In [ ]:
type(StringIO(data))

_io.StringIO

In [ ]:
pd.read_csv(StringIO(data),usecols=['col1','col2'])# to see specific column1

col1 col2
0    x    y
1    a    b
2    1    2

# converting str into csv formate

In [ ]:
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/dataset/mercedesbenz (1).csv',usecols=['X0',	'X1',	'X2',	'X3',	'X4',	'X5'])

In [ ]:
df.head()

X0 X1  X2 X3 X4 X5
0   k  v  at  a  d  u
1   k  t  av  e  d  y
2  az  w   n  c  d  x
3  az  t   n  f  d  x
4  az  v   n  f  d  h

In [ ]:
df.to_csv('test.csv')# this comand just convert this file into csv formate

In [ ]:
df.to_csv('test.csv',index=False)#this just convert file formate into csv but without indexes

# data_type in csv

In [ ]:
data=('col1,col2,col3\n'
      'x,y,z\n'
      'a,b,d\n'
      '1,2,3')

In [ ]:
#import pandas as pd
#from  io import StringIO

# note = it is not required to import  modules and files again and again in same file

In [ ]:
pd.read_csv(StringIO(data))

col1 col2 col3
0    x    y    z
1    a    b    d
2    1    2    3

In [ ]:
df.info()# gives information abot the data in breef

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4209 entries, 0 to 4208
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   X0      4209 non-null   object
 1   X1      4209 non-null   object
 2   X2      4209 non-null   object
 3   X3      4209 non-null   object
 4   X4      4209 non-null   object
 5   X5      4209 non-null   object
dtypes: object(6)
memory usage: 197.4+ KB


In [ ]:
df.isnull().sum()# this will mark 1 infront of that column  in which there is null value

X0    0
X1    0
X2    0
X3    0
X4    0
X5    0
dtype: int64

In [5]:
df.head()

ID       y  X0 X1  X2 X3 X4 X5 X6 X8  ...  X375  X376  X377  X378  X379  \
0   0  130.81   k  v  at  a  d  u  j  o  ...     0     0     1     0     0   
1   6   88.53   k  t  av  e  d  y  l  o  ...     1     0     0     0     0   
2   7   76.26  az  w   n  c  d  x  j  x  ...     0     0     0     0     0   
3   9   80.62  az  t   n  f  d  x  l  e  ...     0     0     0     0     0   
4  13   78.02  az  v   n  f  d  h  d  n  ...     0     0     0     0     0   

   X380  X382  X383  X384  X385  
0     0     0     0     0     0  
1     0     0     0     0     0  
2     0     1     0     0     0  
3     0     0     0     0     0  
4     0     0     0     0     0  

[5 rows x 378 columns]

In [8]:
df['ID']# for printing specific column

0          0
1          6
2          7
3          9
4         13
        ... 
4204    8405
4205    8406
4206    8412
4207    8415
4208    8417
Name: ID, Length: 4209, dtype: int64